const C=[{id:'1',n:'1ª Compañía',a:'Patricio Lynch 1866'},{id:'2',n:'2ª Compañía',a:"Bernardo O'Higgins 909"},{id:'3',n:'3ª Compañía',a:'Av. Juan Mackenna 1259'},{id:'6',n:'6ª Compañía',a:'Antofagasta 640'},{id:'7',n:'7ª Compañía',a:'Felizardo Asenjo 185'},{id:'8',n:'8ª Compañía',a:'Avenida Real 1347'}];
const COL=['#c62828','#1565c0','#2e7d32','#ef6c00','#6a1b9a','#00838f'];
const FUT={lat:-40.5689,lon:-73.128}; const $=id=>document.getElementById(id);
const map=L.map('map').setView([-40.573,-73.135],13); L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:20,attribution:'© OpenStreetMap'}).addTo(map);
let pts=[],markers=[],routeLayer=L.layerGroup().addTo(map),analysisLayer=L.layerGroup().addTo(map),emergency=null,sim=false;
let active=JSON.parse(localStorage.getItem('companies_active')||'null')||C.map(()=>true);
let vehicles=JSON.parse(localStorage.getItem('bomberos_vehicles')||'null')||C.flatMap((c,i)=>[{id:c.id+'-B',name:'B-'+c.id,company:i,kind:'Bomba',available:true},{id:c.id+'-BX',name:'Bx-'+c.id,company:i,kind:'Carro bomba',available:true}]);
function esc(s){return String(s).replace(/[&<>]/g,x=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[x]))}
function save(){localStorage.setItem('companies_active',JSON.stringify(active));localStorage.setItem('bomberos_vehicles',JSON.stringify(vehicles));updateUI()}
function updateUI(){document.querySelectorAll('[data-c]').forEach(x=>{let i=+x.dataset.c;x.checked=active[i];x.closest('.company')?.classList.toggle('off',!active[i])});let n=active.filter(Boolean).length;if($('mapstatus'))$('mapstatus').innerHTML='<b>'+n+'/'+C.length+' compañías activas</b>';markers.forEach((m,i)=>m.setOpacity(active[i]?1:.25));renderVehicles()}
async function geocode(c){let key='station_'+c.id,s=localStorage.getItem(key);if(s)return JSON.parse(s);let q=encodeURIComponent(c.a+', Osorno, Chile');let r=await fetch('https://nominatim.openstreetmap.org/search?format=jsonv2&limit=1&q='+q,{headers:{'Accept-Language':'es'}}),j=await r.json();if(!j[0])throw Error('No se encontró '+c.n);s={lat:+j[0].lat,lon:+j[0].lon};localStorage.setItem(key,JSON.stringify(s));return s}
async function load(){for(let i=0;i<C.length;i++){try{let p=await geocode(C[i]);pts[i]=p;let m=L.marker([p.lat,p.lon],{draggable:true}).addTo(map).bindPopup('<b>🚒 '+C[i].n+'</b><br>'+C[i].a);m.on('dragend',()=>{let q=m.getLatLng();pts[i]={lat:q.lat,lon:q.lng};localStorage.setItem('station_'+C[i].id,JSON.stringify(pts[i]));});markers[i]=m}catch(e){console.warn(e)}await new Promise(r=>setTimeout(r,250))}updateUI();fitAll();}
function fitAll(){let p=pts.filter(Boolean);if(p.length)map.fitBounds(L.latLngBounds(p.map(x=>[x.lat,x.lon])),{padding:[40,40]})}
async function route(p1,p2){let u='https://router.project-osrm.org/route/v1/driving/'+p1.lon+','+p1.lat+';'+p2.lon+','+p2.lat+'?overview=full&geometries=geojson&steps=false';let r=await fetch(u);if(!r.ok)throw Error('OSRM '+r.status);let j=await r.json();return j.routes?.[0]||null}
async function rank(p,draw=true){let out=[];for(let i=0;i<C.length;i++){if(!active[i]||!pts[i])continue;try{let r=await route(pts[i],p);if(r)out.push({i,r})}catch(e){console.warn(e)}}let speed=Math.max(5,+($('speed')?.value||45));out.forEach(x=>x.eta=x.r.distance/1000/speed*60);out.sort((a,b)=>a.eta-b.eta);if(draw){routeLayer.clearLayers();out.forEach((x,z)=>L.geoJSON(x.r.geometry,{style:{color:COL[x.i],weight:z===0?7:3,opacity:z===0?1:.5}}).addTo(routeLayer));}return out}
async function runFirst(p){if(emergency)map.removeLayer(emergency);emergency=L.marker(p).addTo(map).bindPopup('🚨 Emergencia').openPopup();$('ranking').innerHTML='Calculando…';let out=await rank(p,true);$('ranking').innerHTML=out.map((x,z)=>'<div class="rank '+(z?'':'first')+'"><b>#'+(z+1)+' '+C[x.i].n+(z?'':' 🏆')+'</b><br>'+((x.r.distance/1000).toFixed(2))+' km · ETA '+x.eta.toFixed(1)+' min</div>').join('');$('info').innerHTML=out.length?'<b>Primera llegada:</b> '+C[out[0].i].n:'Sin rutas';return out}
map.on('click',e=>{if(sim)runFirst(e.latlng)});
function renderCompanies(){if(!$('companies'))return;$('companies').innerHTML=C.map((c,i)=>'<label class="company"><input type="checkbox" data-c="'+i+'" '+(active[i]?'checked':'')+'><span style="color:'+COL[i]+'">●</span><span><b>'+c.n+'</b><br><small>'+c.a+'</small></span></label>').join('');document.querySelectorAll('[data-c]').forEach(x=>x.onchange=()=>{active[+x.dataset.c]=x.checked;save()})}
function renderVehicles(){if(!$('vehiclelist'))return;$('vehiclelist').innerHTML=vehicles.map((v,i)=>'<div class="vehicle"><b>'+esc(v.name)+'</b> · '+C[v.company].n+'<br><small>'+esc(v.kind)+' · '+(v.available?'DISPONIBLE':'FUERA DE SERVICIO')+'</small><button data-v="'+i+'">'+(v.available?'Desactivar':'Activar')+'</button></div>').join('');document.querySelectorAll('[data-v]').forEach(b=>b.onclick=()=>{vehicles[+b.dataset.v].available=!vehicles[+b.dataset.v].available;save()})}
function renderSelects(){['dispatchCompany','boundaryA','boundaryB'].forEach(id=>{if($(id))$(id).innerHTML=C.map((c,i)=>'<option value="'+i+'">'+c.n+'</option>').join('')})}
async function coverage(){analysisLayer.clearLayers();let bounds=map.getBounds(),n=0,w=0,counts=C.map(()=>0);let lat1=bounds.getSouth(),lat2=bounds.getNorth(),lon1=bounds.getWest(),lon2=bounds.getEast();for(let a=0;a<5;a++)for(let b=0;b<5;b++){let p={lat:lat1+(a+.5)*(lat2-lat1)/5,lon:lon1+(b+.5)*(lon2-lon1)/5};let out=await rank(p,false);if(out.length){counts[out[0].i]++;w++;L.circleMarker([p.lat,p.lon],{radius:8,color:COL[out[0].i],fillOpacity:.55}).addTo(analysisLayer)}}$('coverageResult').innerHTML='<b>'+w+' zonas de prueba analizadas.</b><br>'+counts.map((v,i)=>C[i].n+': '+v+' ('+(w?(v/w*100).toFixed(1):0)+'%)').join('<br>');}
async function boundary(){analysisLayer.clearLayers();let a=+$('boundaryA').value,b=+$('boundaryB').value;if(a===b)return;$('boundaryResult').textContent='Calculando zona de transición…';let bounds=map.getBounds(),pts2=[];for(let i=0;i<7;i++)for(let j=0;j<7;j++){let p={lat:bounds.getSouth()+(i+.5)*(bounds.getNorth()-bounds.getSouth())/7,lon:bounds.getWest()+(j+.5)*(bounds.getEast()-bounds.getWest())/7};let ra=await route(pts[a],p),rb=await route(pts[b],p);if(ra&&rb){let d=Math.abs(ra.duration-rb.duration);if(d<90)pts2.push(p)}}pts2.forEach(p=>L.circleMarker([p.lat,p.lon],{radius:5,color:'#111'}).addTo(analysisLayer));$('boundaryResult').textContent=pts2.length+' puntos de transición aproximados entre '+C[a].n+' y '+C[b].n+'.';}
function futureMarker(on){analysisLayer.clearLayers();if(on)L.marker([FUT.lat,FUT.lon]).addTo(analysisLayer).bindPopup('🏗️ Futuro cuartel 1ª Compañía').openPopup()}
async function compareFuture(p){analysisLayer.clearLayers();let cur=await route(pts[0],p),fut=await route(FUT,p);if(!cur||!fut)return;$('futureResult').innerHTML='<b>1ª Compañía actual:</b> '+(cur.distance/1000).toFixed(2)+' km · '+(cur.duration/60).toFixed(1)+' min<br><b>Futuro:</b> '+(fut.distance/1000).toFixed(2)+' km · '+(fut.duration/60).toFixed(1)+' min';L.geoJSON(cur.geometry,{style:{color:COL[0],weight:4}}).addTo(analysisLayer);L.geoJSON(fut.geometry,{style:{color:'#111',weight:4,dashArray:'8 6'}}).addTo(analysisLayer)}
function stats(){let activeN=active.filter(Boolean).length,avail=vehicles.filter(v=>v.available).length;$('stats').innerHTML='<b>Compañías activas:</b> '+activeN+'/'+C.length+'<br><b>Móviles disponibles:</b> '+avail+'/'+vehicles.length+'<br><b>Posiciones de cuartel:</b> '+pts.filter(Boolean).length+'/'+C.length+'<br><b>Último análisis:</b> '+new Date().toLocaleString('es-CL')}
$('sim').onclick=()=>{sim=!sim;$('simbox').hidden=!sim;$('sim').textContent=sim?'🛑 DESACTIVAR':'ACTIVAR SIMULADOR';map.getContainer().style.cursor=sim?'crosshair':''};$('clear').onclick=()=>{routeLayer.clearLayers();analysisLayer.clearLayers();if(emergency){map.removeLayer(emergency);emergency=null}if($('ranking'))$('ranking').innerHTML=''};$('fitAll').onclick=fitAll;$('reset').onclick=()=>{C.forEach(c=>localStorage.removeItem('station_'+c.id));localStorage.removeItem('companies_active');location.reload()};
$('coverageRun').onclick=coverage;$('boundaryRun').onclick=boundary;$('future').onchange=e=>futureMarker(e.target.checked);$('futureCompare').onclick=()=>{if(emergency)compareFuture(emergency.getLatLng());else $('futureResult').textContent='Active primero el simulador y haga clic en un punto del mapa.'};$('dispatchRun').onclick=async()=>{let p=emergency?.getLatLng();if(!p)return $('dispatchResult').textContent='Haga clic en el mapa con el simulador activo.';let out=await rank(p,false),req=+$('dispatchUnits').value||1;let chosen=[];for(let x of out){let vs=vehicles.filter(v=>v.company===x.i&&v.available&&!chosen.includes(v));for(let v of vs){chosen.push(v);if(chosen.length>=req)break}if(chosen.length>=req)break}$('dispatchResult').innerHTML='<b>Despacho sugerido:</b><br>'+chosen.map(v=>v.name+' — '+C[v.company].n).join('<br>')+'<br><small>'+chosen.length+' móvil(es) seleccionado(s)</small>'};$('scenario').onchange=e=>{active.fill(true);if(e.target.value.startsWith('off-')){let id=e.target.value.split('-')[1],i=C.findIndex(c=>c.id===id);if(i>=0)active[i]=false}save();$('configstatus').textContent='Escenario aplicado.'};
renderCompanies();renderSelects();renderVehicles();CoberturaApp.init();load();